name: Terraform

on:
  push:
    branches:
    - "main"
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    - name: Plan Terraform
      id: plan
      continue-on-error: true
      run: |
        terraform plan > tfplan        
    
#     - name: Reformat Plan
#       if: steps.plan.outcome == 'success'
#       run: |
#         echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
#         | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt          
    
    - name: Put Plan in Env Var
      if: steps.plan.outcome == 'success'
      run: |
        PLAN=$(cat tfplan)
        echo "PLAN<<EOF" >> $GITHUB_ENV
        echo "$PLAN" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Post Plan to GitHub PR
      if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Applying:

          ```diff
          ${{ env.PLAN }}
          ```
    
    - name: Post Plan Failure
      if: steps.plan.outcome == 'failure'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Plan failed for :

          ```
          ${{ steps.plan.outputs.stderr }}
          ``` 
    
    - name: Apply Terraform
      if: steps.plan.outcome == 'success'
      id: apply
      continue-on-error: true
      run: |
        terraform apply -auto-approve > tfapply     
    
    - name: Post Apply to GitHub PR
      if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Applied:

          ```
          echo tfapply
          ```                 

    - name: Post Apply Failure
      if: steps.apply.outcome == 'failure'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Apply failed for :

          ```
          ${{ steps.apply.outputs.stderr }}
          ```       
    - name: commit the terraform state
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        file_pattern: terraform.tfstate
